version: '3.8'

services:
  backend:
    build:
      context: ./backend/overall/overall
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GMAIL_ADDR=${GMAIL_ADDR}
      - GMAIL_APP_PW=${GMAIL_APP_PW}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend/main
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"  # Map port specified in .env file
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
