version: '3.8'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend/overall/overall
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DB_URL=jdbc:mysql://database:${DB_PORT}/${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - GMAIL_ADDR=${GMAIL_ADDR}
      - GMAIL_APP_PW=${GMAIL_APP_PW}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_SOURCE=http://localhost:${FRONTEND_PORT}
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/main
      args:
        - REACT_APP_BACKEND_SOURCE=${REACT_APP_BACKEND_SOURCE}
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"  # Map port specified in .env file
    environment:
      - REACT_APP_BACKEND_SOURCE=${REACT_APP_BACKEND_SOURCE}
    depends_on:
      backend:
        condition: service_started