name: Spring Unit and Integration Tests

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      # Add MySQL service container
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Unit Tests
      working-directory: backend/overall/overall
      run: mvn test -Dtest=!**/*ServiceTest.java
      env:
        DB_URL: jdbc:mysql://localhost:3306/testdb
        DB_USERNAME: root
        DB_PASSWORD: root
        GMAIL_ADDR: ${{ secrets.GMAIL_ADDR }}
        GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        FRONTEND_SOURCE: http://localhost:3000

    - name: Run Integration Tests
      working-directory: backend/overall/overall
      run: mvn test -Dtest=**/*IntegrationTest.java
      env:
        DB_URL: jdbc:mysql://localhost:3306/testdb
        DB_USERNAME: root
        DB_PASSWORD: root
        GMAIL_ADDR: ${{ secrets.GMAIL_ADDR }}
        GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        FRONTEND_SOURCE: http://localhost:3000

    - name: Generate Test Report
      working-directory: backend/overall/overall
      if: always()
      run: mvn surefire-report:report-only

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: backend/overall/overall/target/site/surefire-report.html

    - name: Build with Maven
      working-directory: backend/overall/overall
      if: success()
      run: mvn -B package --file pom.xml -DskipTests

    - name: Upload Build Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: application-jar
        path: backend/overall/overall/target/*.jar
