name: Deploy Frontend

on:
  push:
    branches:
      - sprint-3-main-test-cicd

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Sync frontend to S3
        run: |
          aws s3 sync frontend/build s3://your-s3-bucket-name --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "your-aws-region"
