name: Build Docker Image and Provision Infrastructure with Terraform

on:
  push:
    branches:
      # - main
      - sprint-3-main-test-cicd

jobs:
  build_and_provision:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    # Step 3: Build the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/terraform-deployment:latest .

    # Step 4: Push Docker Image to GitHub Container Registry
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository }}/terraform-deployment:latest

    # Step 5: Install Terraform
    - name: Install Terraform
      run: |
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform -y

    # Step 6: Configure AWS Credentials for Terraform
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    # Step 7: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 8: Destroy Residual Resources (Cleanup)
    - name: Terraform Destroy
      run: terraform destroy -auto-approve

    # Step 9: Reinitialize Terraform
    - name: Terraform Re-Init
      run: terraform init

    # Step 10: Apply Terraform Configuration
    - name: Terraform Apply
      run: terraform apply -auto-approve
